### ISSUE TITLE
Unable to see login credential inputs

### ISSUE THREAD

**Issue by twy30** [OpenPTT/OpenPTT#16]
Environment: WinPro81 + VS2013 + WP81 emulator

Repro: deploy app to emulator and try enter login credentials

No visual feedback when typing with either my physical keyboard or the on-screen virtual keyboard

![screenshot](https://cloud.githubusercontent.com/assets/11057789/8573533/f112df60-2546-11e5-88bc-8edb36cb4595.png)

I can try debugging this, but given that I am new to Cordova, this will take a while

**Comment by ettoolong** [comment]
UI 沒反應我猜是 Onsen 的問題:
下面這篇提到他們有處理,
https://github.com/OnsenUI/OnsenUI/issues/138
我建議你先去弄他們的 sample 來跑, 看看能不能動.
我這邊還暫時沒環境能測.

**Comment by ettoolong** [comment]
這問題不知道查得怎樣了?
似乎和我們用的輸入框元件有關.
在 http://onsen.io/patterns.html 這頁,
Compose 這個 Pattern 的輸入框可以用,
但是 Login 這個 Pattern 的卻不行.

**Comment by ettoolong** [comment]
嘗試修了一下這個問題.
有沒有 有WP環境的人可以幫忙試試?

**Comment by ettoolong** [comment]
經測試已修正
