### ISSUE TITLE
[Ubuntu] cordova dump error "/usr/bin/env: node: No such file or directory"

### ISSUE THREAD

**Issue by verybada** [OpenPTT/OpenPTT#18]
I followed the wiki to setup my environment but I got an error after execute "cordova platform add android"

```
$ cordova platform add android
/usr/bin/env: node: No such file or directory
```

My environment

```
$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"
```

**Comment by verybada** [comment]
According this discussion [here](https://github.com/joyent/node/issues/3911)

Install **nodejs-legacy** can fix this problem

```
$ sudo apt-get install nodejs-legacy
```

**Comment by ensky** [comment]
```
which nodejs
```
if located in /usr/bin/nodejs, then
ln -s /usr/bin/nodejs /usr/bin/node
