### ISSUE TITLE
我的最愛看板若有目錄則會導致 infinite state

### ISSUE THREAD

**Issue by ensky** [OpenPTT/OpenPTT#19]
看起來是會直接卡在 getFavoriteList 的 this.taskStage == 1

**Comment by ettoolong** [comment]
1. Need implement getBoardList task in robot_ptt.js
2. Need handle multi-layer structure.

**Comment by ettoolong** [comment]
我先加一小段 code 避免卡死, 上面兩個部份需要有人實作.

**Comment by ettoolong** [comment]
Fixed.
