### ISSUE TITLE
need require.js or anything else to manage modules

### ISSUE THREAD

**Issue by ensky** [OpenPTT/OpenPTT#20]
It's just a suggestion

**Comment by ettoolong** [comment]
應該可以提高一開始載入的速度, 等功能作差不多後再來處理.

**Comment by ensky** [comment]
主要是modulize, 目前這樣架構dependency不太清楚，新增新module不易

**Comment by ettoolong** [comment]
我不知道這有沒有幫助:
https://github.com/OpenPTT/OpenPTT/wiki/Module-ZH-TW
現在的確有一些模組是互相dependency,
例如 bbsCore create conn(telnet), 而conn又回頭操作bbsCore(一些callback).
我可以把這些都改成 register callback 形式. 你意思是這樣嗎?

**Comment by ensky** [comment]
我的意思是目前所有相依的關係都是直接寫死在zh-tw.html中像是這樣
https://github.com/OpenPTT/OpenPTT/blob/master/www/zh-tw.html#L56-L73
如果我要新增一個file就必須改動到這個檔案、並且要自己依照相關的dependency插入到適當的位置上，才可以運作
若使用一些管理module的工具如require.js可緩解這問題

**Comment by ettoolong** [comment]
有一些東西我不是很確定:
所有的 script 檔也都要用 require([],function(){}); 包起來嗎? 還是只有一開始要load的第一個需要?
感覺如果要幫每個模組都建立dependency tree. 應該都要包?

還有, 因為 require.js 會把你主要的 js 包在它的 scope 裡. code 裡面如果有用到 global 應該要注意.
如果你已經知道怎麼改, 你就直接加吧, 然後 commit 上來.

如果這真的會因為 code 裡原本有的 global 造成問題而沒辦法簡單的改好的話....
我可能需要一點時間來把整份 code 掃一次. 也許是用週六日.

**Comment by ensky** [comment]
ok, 那下週有空的話我會送pull request
btw, module是用define, main才是用require
http://requirejs.org/docs/api.html#defdep

**Comment by ettoolong** [comment]
thx, 學習了.

**Comment by sivid** [comment]
要不要把zh-tw.html和en.html 整合起來?  感覺localization可以用angular做
需要新開一個issue嗎

**Comment by ettoolong** [comment]
開 issue, assign 給你自己, 讓其他人知道你在處理了, 以免重工.

你可以直接改好 push 上來, 頂多先開 branch, 測過沒問題後再 merge.
你也可以 reopen 這條 issue https://github.com/OpenPTT/OpenPTT/issues/6 , assign 給你自己.
