### ISSUE TITLE
Missing repository description or English information

### ISSUE THREAD

**Issue by vi** [OpenPTT/OpenPTT#23]
1. There should be repository description to help search for the project on Github;
2. There should be at least short fragment in repository description and README about what the project does in English;
3. Usage of "PPT" meaning "presentation" is probably discouraged as Microsoft-centric, unless the project deals with actual PowerPoint presentations.

**Comment by ettoolong** [comment]
1. Add description now.
2. Add description in README
3. This is a mobile app for BBS site ptt.cc (PTT)
   see: https://www.ptt.cc/index.html  (It's a Traditional Chinese site)
