### ISSUE TITLE
[求助] android模擬器畫面跑掉

### ISSUE THREAD

**Issue by iamso1** [OpenPTT/OpenPTT#28]
Hi 大家好,
我按照 [GettingStarted-ZH-TW](https://github.com/OpenPTT/OpenPTT/wiki/GettingStarted-ZH-TW)安裝完環境, 並嘗試運行在android模擬器上時, 畫面如下:
請問有人跟我一樣嗎? 是不是需要再調整什麼?  
![AVD 畫面](http://i.imgur.com/G2yq7nS.png)

**Comment by ettoolong** [comment]
應該跟 https://github.com/OpenPTT/OpenPTT/pull/26 有關.
這畫面像是 AngularJS 沒跑起來.

**Comment by ensky** [comment]
在我這邊無法重現，我模擬器第一秒的話面如圖所示，之後就會正常了。

**Comment by ettoolong** [comment]
先 debug 看看吧, 參考 https://github.com/OpenPTT/OpenPTT/wiki/Debugging
在 chrome 裡面網址 Chrome://inspect 連進去看有沒有錯誤訊息,
然後到 main.js 裡面加一些 console.log, 看看 angular.bootstrap(document, ['app']); 這行有沒有進去.

**Comment by Jackmoo** [comment]
我之前也有這個問題
但是今天重新git clone了一份最新的commit 重新弄環境之後就好了 不確定是不是之前的commit造成的

另外這次有遇到Error: EXDEV, cross-device link not permitted這個問題, 改用那個work around
emulator有多勾一個wipe user data的選項 不知道有沒有影響

**Comment by ettoolong** [comment]
這問題新版應該是不會發生了, close. 有再遇到再 reopen.
