### ISSUE TITLE
已登入情況下，在主選單按下返回，不應回到登入畫面

### ISSUE THREAD

**Issue by ensky** [OpenPTT/OpenPTT#31]
此時應該彈出確認離開視窗，若選擇是，則直接關閉程式之類的

**Comment by ettoolong** [comment]
參考 http://onsen.io/reference/ons-navigator.html#event-prepop
設定 navigator 的 prepop 事件, 然後用 event.cancel 取消掉 pop 或作其他處理.
如果是要 關閉程式 可能要看 cordova 怎麼在網頁裡把自己關掉.

**Comment by elfsu** [comment]
或者，登入後把登入頁從STACK還是QUEUE裡拿掉？

2015-07-31 0:31 GMT+08:00 ettoolong notifications@github.com:
