### ISSUE TITLE
需要實作 i18n 的部份

### ISSUE THREAD

**Issue by ettoolong** [OpenPTT/OpenPTT#6]
要上架的最低限度是英文介面, 所以要支援有中英兩個語系的UI

**Comment by ettoolong** [comment]
看看這個能不能用
https://github.com/apache/cordova-plugin-globalization
cordova 官網是說用這個.

**Comment by ug945** [comment]
已實作用 https://github.com/apache/cordova-plugin-globalization 偵測環境語言並加入繁中(zh-tw)語系

**Comment by sivid** [comment]
研究看看用angular把zh-tw.html和en.html合併的可行性

**Comment by verybada** [comment]
https://github.com/doshprompt/angular-localization
這個合用嗎?

**Comment by ettoolong** [comment]
應該是沒問題了, 謝謝.
